model:
  type: BernoulliNB
  alpha: .7
  fit_prior: true
split:
  test_size: 0.2
  random_state: 42
paths:
  raw_data: data/raw/telco_churn.csv
  processed_data: data/processed/telco_clean.csv
  model_path: models/churn_model.pkl
  metrics_path: metrics.json
